### ISSUE TITLE
Trailing zeroes in factorial

### ISSUE THREAD

**Issue by ghost** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#10]
###  Give File Name :  `Trailing-Zero-In-Fact`  ✅ In respective language folder  
# 📑 DESCRIPTION
## [Trailing zeroes in factorial](https://practice.geeksforgeeks.org/problems/trailing-zeroes-in-factorial5134/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

For an integer N find the number of trailing zeroes in N!.
You may assume that each input would have **exactly one solution**, and you may not use the same element twice.
You can return the answer in any order.

**Example 1:**
```
Input:
N = 5
Output:
1
Explanation:
5! = 120 so the number of trailing zero is 1.
```
**Example 2:**
```
Input:
N = 4
Output:
0
Explanation:
4! = 24 so the number of trailing zero is 0.
```
**Constraints:**
```
-1 <= N <= 109
```
**Your Task:**
```
You don't need to read input or print anything. Your task is to complete the function
trailingZeroes() which take an integer N as an input parameter and returns the count of trailing zeroes in the N!.
```

**Expected Time Complexity:**  O(logN)
**Expected Auxiliary Space:**  O(1)

**Comment by compiledbyme** [comment]
Assign me this issue

**Comment by Zohaib-4** [comment]
Kindly assign me this issue as I am a beginner in open source contributions and want to start from somewhere but have good knowledge of programming mainly in C++.

**Comment by hlw-aryan** [comment]
Please assign this task to me. I believe I can efficiently solve this data structure and algorithm problem with a time complexity of O(log5(n)).
@vivekPatil45

**Comment by vivekPatil45** [comment]
fixee: #19

**Comment by vivekPatil45** [comment]
PR: #19
