### ISSUE TITLE
DFS of Graph

### ISSUE THREAD

**Issue by Paresh-95** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#153]
###  Give File Name :  `DFSGraph`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [DFS of Graph](https://practice.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1?page=1&category[]=Graph&sortBy=submissions)

![Difficulty: Medium](https://img.shields.io/badge/Difficulty-Medium-yellow)

You are given a connected undirected graph. Perform a Depth First Traversal of the graph.

**Example 1:**
```
Input: V = 5 , adj = [[2,3,1] , [0], [0,4], [0], [2]]
Output: 0 2 4 3 1
Explanation: 
0 is connected to 2, 3, 1.
1 is connected to 0.
2 is connected to 0 and 4.
3 is connected to 0.
4 is connected to 2.
so starting from 0, it will go to 2 then 4,
and then 3 and 1.
Thus dfs will be 0 2 4 3 1.
```
**Example 2:**
```
Input: V = 4, adj = [[1,3], [2,0], [1], [0]]
Output: 0 1 2 3
Explanation:
0 is connected to 1 , 3.
1 is connected to 0, 2. 
2 is connected to 1.
3 is connected to 0. 
so starting from 0, it will go to 1 then 2
then back to 0 then 0 to 3
thus dfs will be 0 1 2 3. 
```

**Constraints:**
```
1 ≤ V, E ≤ 104
- Only one valid answer exists.
```

**Comment by SayaliMarathe-13** [comment]
please assign this to me

**Comment by Sayan2908** [comment]
Can you assign this to me

**Comment by Paresh-95** [comment]
assigned to @SayaliMarathe-13
