### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#16]
###  Give File Name :  `Kadanes-algo`  ✅ In respective language folder  
# 📑 DESCRIPTION
## [Kadane's Algorithm](https://practice.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1)

![Difficulty: Medium](https://img.shields.io/badge/Difficulty-Medium-yellow)

Given an array Arr[] of N integers. Find the contiguous sub-array(containing at least one number) which has the maximum sum and return its sum.

**Example 1:**
```
Input:
N = 5
Arr[] = {1,2,3,-2,5}
Output:
9
Explanation:
Max subarray sum is 9
of elements (1, 2, 3, -2, 5) which 
is a contiguous subarray.
```
**Example 2:**
```
Input:
N = 4
Arr[] = {-1,-2,-3,-4}
Output:
-1
Explanation:
Max subarray sum is -1 
of element (-1)
```

**Constraints:**
```
1 ≤ N ≤ 106
-107 ≤ A[i] ≤ 107
```
**Expected Time Complexity:**  O(N)
**Expected Auxiliary Space:**  O(1)

**Comment by Mr-Yash-beldar** [comment]
Assign this issue to me
