### ISSUE TITLE
Reverse Integer

### ISSUE THREAD

**Issue by ghost** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#21]
###  Give File Name :  `Reverse_Integer`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Reverse Integer](https://leetcode.com/problems/reverse-integer/)

![Difficulty: Medium](https://img.shields.io/badge/Difficulty-Medium-yellow)

 <hr><p>Given a signed 32-bit integer <code>x</code>, return <code>x</code><em> with its digits reversed</em>. If reversing <code>x</code> causes the value to go outside the signed 32-bit integer range <code>[-2<sup>31</sup>, 2<sup>31</sup> - 1]</code>, then return <code>0</code>.</p>

<p><strong>Assume the environment does not allow you to store 64-bit integers (signed or unsigned).</strong></p>

<p>&nbsp;</p>
<p><strong class="example">Example 1:</strong></p>

<pre>
<strong>Input:</strong> x = 123
<strong>Output:</strong> 321
</pre>

<p><strong class="example">Example 2:</strong></p>

<pre>
<strong>Input:</strong> x = -123
<strong>Output:</strong> -321
</pre>

<p><strong class="example">Example 3:</strong></p>

<pre>
<strong>Input:</strong> x = 120
<strong>Output:</strong> 21
</pre>

<p>&nbsp;</p>
<p><strong>Constraints:</strong></p>

<ul>
	<li><code>-2<sup>31</sup> &lt;= x &lt;= 2<sup>31</sup> - 1</code></li>
</ul>

**Comment by Freakyab** [comment]
can you assign it to me

**Comment by ghost** [comment]
@Freakyab ,
This issue is assigned to You.
