### ISSUE TITLE
Leaders in an array

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#25]
###   Give File Name :  `Leader_In_Array`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Leaders in an array](https://practice.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given an array A of positive integers. Your task is to find the leaders in the array. An element of array is leader if it is greater than or equal to all the elements to its right side. The rightmost element is always a leader. 

**Example 1:**
```
Input:
n = 6
A[] = {16,17,4,3,5,2}
Output: 17 5 2
Explanation: The first leader is 17 
as it is greater than all the elements
to its right.  Similarly, the next 
leader is 5. The right most element 
is always a leader so it is also 
included.
```
**Example 1:**
```
Input:
n = 5
A[] = {1,2,3,4,0}
Output: 4 0
Explanation: 0 is the rightmost element
and 4 is the only element which is greater
than all the elements to its right.
```

**Constraints:**
```
1 <= n <= 107
0 <= Ai <= 107
```
**Task:**
```
You don't need to read input or print anything. The task is to complete
the function leader() which takes array A and n as input parameters and 
returns an array of leaders in order of their appearance.
```

**Comment by NigeeHettige** [comment]
Hi,
Can you assign me to this?

**Comment by Subhashini014** [comment]
Hello could you please assign me this issue.

**Comment by Samihan15** [comment]
hello @vivekPatil45  can you assign it to me ?

**Comment by vivekPatil45** [comment]
@Samihan15  this issue is assign to you
