### ISSUE TITLE
Number of 1 Bits

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#26]
###  Give File Name :  `Number_Of_1_Bits`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Number of 1 Bits](https://practice.geeksforgeeks.org/problems/set-bits0143/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given a positive integer N, print count of set bits in it. 

**Example 1:**
```
IInput:
N = 6
Output:
2
Explanation:
Binary representation is '110' 
So the count of the set bit is 2.
```
**Example 2:**
```
Input:
8
Output:
1
Explanation:
Binary representation is '1000' 
So the count of the set bit is 1.
```

**Constraints:**
```
1 ≤ N ≤ 109
```

**Comment by Freakyab** [comment]
can you assign this to me !

**Comment by NigeeHettige** [comment]
Hi,
Can you assign me to this?

**Comment by Virtual4087** [comment]
@vivekPatil45 can you check my pr?

**Comment by Mr-Yash-beldar** [comment]
Assign this issue to me I am from RCPIT

**Comment by vivekPatil45** [comment]
@Mr-Yash-beldar  solve this issue

**Comment by imshaaz21** [comment]
Could you please assign me this issue?
