### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#27]
###  Give File Name :  `Selection_Sort`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Selection Sort](https://practice.geeksforgeeks.org/problems/selection-sort/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given an unsorted array of size N, use selection sort to sort arr[] in increasing order.

**Example 1:**
```
Input:
N = 5
arr[] = {4, 1, 3, 9, 7}
Output:
1 3 4 7 9
Explanation:
Maintain sorted (in bold) and unsorted subarrays.
Select 1. Array becomes 1 4 3 9 7.
Select 3. Array becomes 1 3 4 9 7.
Select 4. Array becomes 1 3 4 9 7.
Select 7. Array becomes 1 3 4 7 9.
Select 9. Array becomes 1 3 4 7 9.
```

```
Expected Time Complexity: O(N2)
Expected Auxiliary Space: O(1)
```

**Comment by Freakyab** [comment]
can you assign it to me !

**Comment by NigeeHettige** [comment]
Hi,
Can you assign me to this?

**Comment by Subhashini014** [comment]
could you please assign me this issue.

**Comment by Harsh76200** [comment]
I will take care of it.. Harsh Jain from RCPIT

**Comment by vivekPatil45** [comment]
@Harsh76200  solve it
