### ISSUE TITLE
Rotate Array

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#30]
###  Give File Name :  `Rotate_Array`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Rotate Array](https://practice.geeksforgeeks.org/problems/rotate-array-by-n-elements-1587115621/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given an unsorted array arr[] of size N. Rotate the array to the left (counter-clockwise direction) by D steps, where D is a positive integer. 

**Example 1:**
```
Input:
N = 5, D = 2
arr[] = {1,2,3,4,5}
Output: 3 4 5 1 2
Explanation: 1 2 3 4 5  when rotated
by 2 elements, it becomes 3 4 5 1 2.
```
**Example 2:**
```
Input:
N = 10, D = 3
arr[] = {2,4,6,8,10,12,14,16,18,20}
Output: 8 10 12 14 16 18 20 2 4 6
Explanation: 2 4 6 8 10 12 14 16 18 20 
when rotated by 3 elements, it becomes 
8 10 12 14 16 18 20 2 4 6.
```

**Task:**
```
You need not print or read anything. You need to complete the function rotateArr() which takes 
the array, D and N as input parameters and rotates the array by D elements. 
The array must be modified in-place without using extra space. 
```

**Comment by DarkSoul26** [comment]
Let me take a look into this @vivekPatil45

**Comment by Akash7649** [comment]
Hey @vivekPatil45 I would like to solve this please assign me this issue under hacktoberfestt2023

**Comment by NigeeHettige** [comment]
Hi,
I would like to work on this.

**Comment by Subhashini014** [comment]
Hello Could you please assign me this issue.

**Comment by Dinesh-Deore1** [comment]
Assign this issue I am from RCPIT.
