### ISSUE TITLE
Second Largest

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#40]
###  Give File Name :  `Second_largest`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Second Largest](https://practice.geeksforgeeks.org/problems/second-largest3735/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given an array Arr of size N, print second largest distinct element from an array.

**Example 1:**
```
Input: 
N = 6
Arr[] = {12, 35, 1, 10, 34, 1}
Output: 34
Explanation: The largest element of the 
array is 35 and the second largest element
is 34.
```
**Example 2:**
```
Input: 
N = 3
Arr[] = {10, 5, 10}
Output: 5
Explanation: The largest element of 
the array is 10 and the second 
largest element is 5.
```

```
Expected Time Complexity: O(N)
Expected Auxiliary Space: O(1)
```

**Comment by Mr-Yash-beldar** [comment]
Assign this issue to me I am from RCPIT
