### ISSUE TITLE
Prime Factors

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#48]
###  Give File Name :  `Prime_Factor`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Prime Factors](https://practice.geeksforgeeks.org/problems/prime-factors5052/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given a number N. Find its unique prime factors in increasing order.
 
**Example 1:**
```
Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].
```
**Example 2:**
```
Input: N = 35
Output: 5 7
Explanation: 5 and 7 are the unique prime
factors of 35.

```

```
Expected Time Complexity: O(N)
Expected Space Complexity: O(N)
 
```

**Comment by nikhilbhalkar** [comment]
I would like to solve this issue, assign to me ,i am from RCPIT

**Comment by vivekPatil45** [comment]
@nikhilbhalkar  solve this issue
