### ISSUE TITLE
Wave Array

### ISSUE THREAD

**Issue by Harsh76200** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#51]
###  Give File Name :  `Wave_Array`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Wave_Array](https://practice.geeksforgeeks.org/problems/wave-array-1587115621/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given a sorted array arr[] of distinct integers. Sort the array into a wave-like array(In Place).
In other words, arrange the elements into a sequence such that arr[1] >= arr[2] <= arr[3] >= arr[4] <= arr[5].....

If there are multiple solutions, find the lexicographically smallest one.

Note: The given array is sorted in ascending order, and you don't need to return anything to make changes in the original array itself.

**Example 1:**
```
Input:
n = 5
arr[] = {1,2,3,4,5}
Output: 2 1 4 3 5
Explanation: Array elements after 
sorting it in wave form are 
2 1 4 3 5.
```
**Example 2:**
```
Input:
n = 6
arr[] = {2,4,7,8,9,10}
Output: 4 2 8 7 10 9
Explanation: Array elements after 
sorting it in wave form are 
4 2 8 7 10 9.
```

Your Task:
The task is to complete the function convertToWave(), which converts the given array to a wave array.

**Comment by rushi173** [comment]
@Harsh76200  Please assign me  for this issues I am from RCPIT
