### ISSUE TITLE
Kth Largest Element in an Array

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#52]
###  Give File Name :  `KthLargestElement`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Kth Largest Element in an Array](https://leetcode.com/problems/kth-largest-element-in-an-array/)

![Difficulty: Medium](https://img.shields.io/badge/Difficulty-Medium-yellow)

Given an integer array nums and an integer k, return the kth largest element in the array.
Note that it is the kth largest element in the sorted order, not the kth distinct element.

Can you solve it without sorting?

**Example 1:**
```
Input: nums = [3,2,1,5,6,4], k = 2
Output: 5
```
**Example 2:**
```
Input: nums = [3,2,3,1,2,4,5,5,6], k = 4
Output: 4
```

**Constraints:**
```
1 <= k <= nums.length <= 10^5
10^4 <= nums[i] <= 104
```

**Comment by MeetD99** [comment]
I would like to work on this issue. Can you please assign it to me.

**Comment by Vybhavigithub** [comment]
@vivekPatil45 Could you please assign this task to me. I would like to contribute.

**Comment by jayeshs08** [comment]
hey @vivekPatil45 can you please assign this issue to me? I can contribute to the repository using different languages. Thankyou!

**Comment by Ferdinand-Ogama** [comment]
Hello, is it possible to work on these issues without being assigned? 
I have checked the Read.Me file and I haven't seen anything related to this, which is why I'm asking.

**Comment by Harsh76200** [comment]
@vivekPatil45 Let me solve this..

**Comment by saurabhm02** [comment]
@vivekPatil45  hey can u assign me this  i can solve this problem from brute-force approach to very optimal solution

**Comment by nikhilbhalkar** [comment]
I would like to solve this issue , from RCPIT

**Comment by vivekPatil45** [comment]
@nikhilbhalkar solve it

**Comment by nikhilbhalkar** [comment]
ok bro
