### ISSUE TITLE
Implement Queue using Stacks

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#53]
###  Give File Name :  `QueueUsingStacks`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Implement Queue using Stacks](https://leetcode.com/problems/implement-queue-using-stacks/)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Implement a first in first out (FIFO) queue using only two stacks. The implemented queue should support all the functions of a normal queue (push, peek, pop, and empty).

### MyQueue Class

- `void push(int x)`: Pushes element `x` to the back of the queue.
- `int pop()`: Removes the element from the front of the queue and returns it.
- `int peek()`: Returns the element at the front of the queue.
- `boolean empty()`: Returns `true` if the queue is empty, `false` otherwise.

**Example 1:**
```
Input
["MyQueue", "push", "push", "peek", "pop", "empty"]
[[], [1], [2], [], [], []]
Output
[null, null, null, 1, 1, false]

Explanation
MyQueue myQueue = new MyQueue();
myQueue.push(1); // queue is: [1]
myQueue.push(2); // queue is: [1, 2] (leftmost is front of the queue)
myQueue.peek(); // return 1
myQueue.pop(); // return 1, queue is [2]
myQueue.empty(); // return false
```

### Constraints

- `1 <= x <= 9`
- At most 100 calls will be made to `push`, `pop`, `peek`, and `empty`.
- All the calls to `pop` and `peek` are valid.

**Comment by gitaditee** [comment]
@vivekPatil45 can you please assign this task to me

**Comment by imshaaz21** [comment]
@vivekPatil45 Could you please assign me this issue?

**Comment by 1Mangesh1** [comment]
### Assign me ! @vivekPatil45

**Comment by suraakhila1** [comment]
could you please assign me this work i am excited to work on it

**Comment by vivekPatil45** [comment]
@1Mangesh1 solve it
