### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#54]
###  Give File Name :  `BubbleSort`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Bubble Sort](https://practice.geeksforgeeks.org/problems/bubble-sort/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given an Integer N and a list arr. Sort the array using bubble sort algorithm.

**Example 1:**
```
Input: 
N = 5
arr[] = {4, 1, 3, 9, 7}
Output: 
1 3 4 7 9
```
**Example 2:**
```
Input:
N = 10 
arr[] = {10, 9, 8, 7, 6, 5, 4, 3, 2, 1}
Output: 
1 2 3 4 5 6 7 8 9 10

```

```
Expected Time Complexity: O(N^2).
Expected Auxiliary Space: O(1).
```

**Comment by Harsh76200** [comment]
@vivekPatil45 please assign it to me..

**Comment by vivekPatil45** [comment]
@Harsh76200 solve it
