### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#55]
###  Give File Name :  `MergeSort`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Merge Sort](https://practice.geeksforgeeks.org/problems/merge-sort/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given an array arr[], its starting position l and its ending position r. Sort the array using merge sort algorithm.

**Example 1:**
```
Input: 
N = 5
arr[] = {4, 1, 3, 9, 7}
Output: 
1 3 4 7 9
```
**Example 2:**
```
Input:
N = 10 
arr[] = {10, 9, 8, 7, 6, 5, 4, 3, 2, 1}
Output: 
1 2 3 4 5 6 7 8 9 10

```

```
Expected Time Complexity: O(nlogn) 
Expected Auxiliary Space: O(n)

```

**Comment by Harsh76200** [comment]
@vivekPatil45 let me do this...

**Comment by vivekPatil45** [comment]
@Harsh76200  solve it

**Comment by gitaditee** [comment]
@vivekPatil45 can you please assign this task to me I want to contribute

**Comment by imshaaz21** [comment]
Could you please assign me this issue?

**Comment by imshaaz21** [comment]
@vivekPatil45 Could you please assign me this issue?

**Comment by jayeshs08** [comment]
Hey @vivekPatil45 can you assign this to me? I can contribute to it using multiple languages and proper formatted code.

**Comment by Samihan15** [comment]
@vivekPatil45 can you assign this task to me ?

**Comment by vivekPatil45** [comment]
@Samihan15 solve it
