### ISSUE TITLE
Print first n Fibonacci Numbers

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#56]
###  Give File Name :  `filename`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Print first n Fibonacci Numbers](https://practice.geeksforgeeks.org/problems/print-first-n-fibonacci-numbers1002/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given a number N, find the first N Fibonacci numbers. The first two number of the series are 1 and 1.

**Example 1:**
```
Input:
N = 5
Output: 1 1 2 3 5

```
**Example 2:**
```
Input:
N = 7
Output: 1 1 2 3 5 8 13
```

**Constraints:**
```
Expected Time Complexity: O(N).
Expected Auxiliary Space: O(N).
```

**Your task** 
```
Your task is to complete printFibb() which takes single argument N and returns a list of first N Fibonacci numbers.
```

**Comment by nikhilbhalkar** [comment]
Hi, assign this issue to me , from RCPIT

**Comment by vivekPatil45** [comment]
@nikhilbhalkar solve it

**Comment by nikhilbhalkar** [comment]
ok @vivekPatil45

**Comment by gitaditee** [comment]
@vivekPatil45 can you please assign this task to me I want to contribute

**Comment by Vybhavigithub** [comment]
@vivekPatil45 could you please assign this task to me. I would like to contribute
