### ISSUE TITLE
Euclidean Algorithm

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#57]
###  Give File Name :  `EuclideanAlgorithm`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Euclidean Algorithm](https://www.codingninjas.com/studio/library/gcd-euclidean-algorithm)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given two positive integers A and B, find GCD of A and B.

**Example 1:**
```
Input: A = 3, B = 6
Output: 3
Explanation: GCD of 3 and 6 is 3
```
**Example 2:**
```
Input: A = 1, B = 1
Output: 1
Explanation: GCD of 1 and 1 is 1
```

```
Expected Time Complexity: O(log(min(A, B)))
Expected Auxiliary Space: O(1)
```

**Comment by nikhilbhalkar** [comment]
Hi , assign this issue to me , from RCPIT

**Comment by vivekPatil45** [comment]
@nikhilbhalkar solve it

**Comment by gitaditee** [comment]
@vivekPatil45 can you please assign this task to me ,,I want to contribute
