### ISSUE TITLE
Second Largest

### ISSUE THREAD

**Issue by Harsh76200** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#61]
###  Give File Name :  `Second Largest`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Second Largest](https://practice.geeksforgeeks.org/problems/second-largest3735/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given an array Arr of size N, print second largest distinct element from an array.

**Example 1:**
```
Input: 
N = 6
Arr[] = {12, 35, 1, 10, 34, 1}
Output: 34
Explanation: The largest element of the 
array is 35 and the second largest element
is 34.
```
**Example 2:**
```
Input: 
N = 3
Arr[] = {10, 5, 10}
Output: 5
Explanation: The largest element of 
the array is 10 and the second 
largest element is 5.
```

**Follow-up:** Expected Time Complexity: O(N)  Expected Auxiliary Space: O(1)

**Comment by Vayras** [comment]
Hi @Harsh76200  I would like to work on this issue

**Comment by Dinesh-Deore1** [comment]
Assign this issue to me.

**Comment by suraakhila1** [comment]
please assign this issue to me sir.

**Comment by vivekPatil45** [comment]
@Dinesh-Deore1 solve it
