### ISSUE TITLE
Check if array is sorted

### ISSUE THREAD

**Issue by Harsh76200** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#62]
###  Give File Name :  `Check if array is sorted`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Check if array is sorted](https://practice.geeksforgeeks.org/problems/check-if-an-array-is-sorted0701/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given an array arr[] of size N, check if it is sorted in non-decreasing order or not. 

**Example 1:**
```
Input:
N = 5
arr[] = {10, 20, 30, 40, 50}
Output: 1
Explanation: The given array is sorted.
```
**Example 2:**
```
Input:
N = 6
arr[] = {90, 80, 100, 70, 40, 30}
Output: 0
Explanation: The given array is not sorted.
```

**Follow-up:** Expected Time Complexity: O(N) Expected Auxiliary Space: O(1)

**Comment by SumitMangrati** [comment]
hey can you assign me this issue i'll get it done

**Comment by suhelBhadane** [comment]
Assign this issue to me. I am from RCPIT.
