### ISSUE TITLE
Linked List Insertion

### ISSUE THREAD

**Issue by Harsh76200** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#68]
###  Give File Name :  `Linked List Insertion`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Linked List Insertion](https://practice.geeksforgeeks.org/problems/linked-list-insertion-1587115620/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Create a link list of size N according to the given input literals. Each integer input is accompanied by an indicator which can either be 0 or 1. If it is 0, insert the integer in the beginning of the link list. If it is 1, insert the integer at the end of the link list. 
Hint: When inserting at the end, make sure that you handle NULL explicitly.

**Example 1:**
```
Input:
LinkedList: 9->0->5->1->6->1->2->0->5->0
Output: 5 2 9 5 6
Explanation:
Length of Link List = N = 5
9 0 indicated that 9 should be
inserted in the beginning. Modified
Link List = 9.
5 1 indicated that 5 should be
inserted in the end. Modified Link
List = 9,5.
6 1 indicated that 6 should be
inserted in the end. Modified Link
List = 9,5,6.
2 0 indicated that 2 should be
inserted in the beginning. Modified
Link List = 2,9,5,6.
5 0 indicated that 5 should be
inserted in the beginning. Modified
Link List = 5,2,9,5,6. 
Final linked list = 5, 2, 9, 5, 6.
```
**Example 2:**
```
Input:
LinkedList: 5->1->6->1->9->1
Output: 5 6 9
```

**Follow-up:** Can you come up with an algorithm that is less than O(n^2) time complexity?

**Comment by GRINGOLOCO7** [comment]
Hello, how are you?
I think I solved this problem... check my pull request (https://github.com/Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub/pull/74)

**Comment by adv8j** [comment]
Hi! I'd like to solve the problem in C so could you assign it to me?
