### ISSUE TITLE
DFS of Graph

### ISSUE THREAD

**Issue by Harsh76200** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#69]
###  Give File Name :  `DFS of Graph`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [DFS of Graph](https://practice.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

You are given a connected undirected graph. Perform a Depth First Traversal of the graph.
Note: Use the recursive approach to find the DFS traversal of the graph starting from the 0th vertex from left to right according to the graph.

**Example 1:**
```
Input: V = 5 , adj = [[2,3,1] , [0], [0,4], [0], [2]]
Output: 0 2 4 3 1
Explanation: 
0 is connected to 2, 3, 1.
1 is connected to 0.
2 is connected to 0 and 4.
3 is connected to 0.
4 is connected to 2.
so starting from 0, it will go to 2 then 4,
and then 3 and 1.
Thus dfs will be 0 2 4 3 1.
```

**Follow-up:** Can you come up with an algorithm that is less than O(n^2) time complexity?

**Comment by Shreya111111** [comment]
@Harsh76200 assign this to me for java

**Comment by charviupreti** [comment]
@Harsh76200 Can you assign this to me for python?

**Comment by Harsh76200** [comment]
@Shreya111111 solve

**Comment by GitanshuA** [comment]
I can do it for C++. Can you please assign it to me?
