### ISSUE TITLE
Insert a node in a BST

### ISSUE THREAD

**Issue by Harsh76200** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#70]
###  Give File Name :  `Insert a node in a BST`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Insert a node in a BST](https://practice.geeksforgeeks.org/problems/insert-a-node-in-a-bst/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given a BST and a key K. If K is not present in the BST, Insert a new Node with a value equal to K into the BST. If K is already present in the BST, don't modify the BST.

**Example 1:**
```
Input:
     2
   /   \   
  1     3
K = 4
Output: 
1 2 3 4
Explanation: 
After inserting the node 4
Inorder traversal will be 1 2 3 4.
```
**Example 2:**
```
Input:
        2
      /   \
     1     3
             \
              6
K = 4
Output: 
1 2 3 4 6
Explanation: 
After inserting the node 4
Inorder traversal of the above tree will be 1 2 3 4 6.
```

**Follow-up:** Can you come up with an algorithm that is less than O(n^2) time complexity?

**Comment by rushi173** [comment]
@Harsh76200  Please Assign me for this issue I provide solution in java I am from RCPIT

**Comment by Faizanusmani06** [comment]
@Harsh76200 Can you assign this issue to me? I can solve this problem in C++.

**Comment by Shreya111111** [comment]
@Harsh76200  assign this to me for python

**Comment by adv8j** [comment]
Hi! I can provide a solution in C, so could you please assign this to me?

**Comment by Harsh76200** [comment]
@rushi173 solve it
