### ISSUE TITLE
Reverse a String

### ISSUE THREAD

**Issue by Harsh76200** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#86]
###  Give File Name :  `Reverse a String`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Reverse a String](https://practice.geeksforgeeks.org/problems/reverse-a-string/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

You are given a string s. You need to reverse the string.

**Example 1:**
```
Input:
s = Geeks
Output: skeeG
```
**Example 2:**
```
Input:
s = for
Output: rof
```

**Follow-up:** Can you come up with an algorithm that is less than O(n^2) time complexity?

**Comment by georgioupanayiotis** [comment]
@Harsh76200  can you assign this to me ?

**Comment by Dinesh-Deore1** [comment]
Assign this to me.

**Comment by Paresh-95** [comment]
Assign this to me RCPIT

**Comment by vivekPatil45** [comment]
@Dinesh-Deore1 solve it
