### ISSUE TITLE
Uncommon characters

### ISSUE THREAD

**Issue by Harsh76200** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#88]
###  Give File Name :  `Uncommon characters`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Uncommon characters](https://practice.geeksforgeeks.org/problems/uncommon-characters4932/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given two strings A and B consisting of lowercase english characters. Find the characters that are not common in the two strings. 

Note :- Return the string in sorted order..

**Example 1:**
```
Input:
A = geeksforgeeks
B = geeksquiz
Output: fioqruz
Explanation: 
The characters 'f', 'i', 'o', 'q', 'r', 'u','z' 
are either present in A or B, but not in both.
```
**Example 2:**
```
Input:
A = characters
B = alphabets
Output: bclpr
Explanation: The characters 'b','c','l','p','r' 
are either present in A or B, but not in both.
```

**Follow-up:** Can you come up with an algorithm that is less than O(n^2) time complexity?

**Comment by georgioupanayiotis** [comment]
@Harsh76200 can you assign this to me please?

**Comment by gilbert-keter** [comment]
Can i do this sir

**Comment by georgioupanayiotis** [comment]
@Harsh76200  created c program  PR [here](https://github.com/Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub/pull/92)

**Comment by Pankaj4152** [comment]
Can you please assign this to me for a Python based solution?

**Comment by hlw-aryan** [comment]
Can you please assign this issue to me, I can solve this in Time Complexity: O(n) 
@Harsh76200

**Comment by Pankaj4152** [comment]
@Harsh76200  Can you assign this to me? for python based solution

**Comment by rushi173** [comment]
@Harsh76200  Can you assign me for this issues ?
