### ISSUE TITLE
Find Position of First Set Bit in Binary Representation

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#9]
# 📑 DESCRIPTION

## [Find First Set Bit](https://practice.geeksforgeeks.org/problems/find-first-set-bit-1587115620/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given an integer `N`. The task is to return the position of first set bit found from the `right` side in the binary representation of the number.
Note: If there is no set bit in the integer N, then return 0 from the function

**Example 1:**
```
Input: 
N = 18
Output: 
2
Explanation: 
Binary representation of 18 is 010010,the first set bit from the right side is at position 2.
```
**Example 2:**
```
Input: 
N = 12 
Output: 
3 
Explanation: 
Binary representation of  12 is 1100, the first set bit from the right side is at position 3.
```

**Your Task:**
```
The task is to complete the function getFirstSetBit() that takes an integer n as a parameter 
and returns the position of first set bit.
```

**Constraints:**
```
0 <= N <= 108
```

**Comment by Virtual4087** [comment]
assign me

**Comment by Virtual4087** [comment]
Check

**Comment by AviGawande** [comment]
would be glad if you assigned me this task to work on .
