### ISSUE TITLE
Valid Palindrome

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#93]
###  Give File Name :  `valid_palindrome`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Valid Palindrome](https://leetcode.com/problems/valid-palindrome/description/)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers.

Given a string s, return true if it is a palindrome, or false otherwise.

**Example 1:**
```
Input: s = "A man, a plan, a canal: Panama"
Output: true
Explanation: "amanaplanacanalpanama" is a palindrome.
```
**Example 2:**
```
Input: s = "race a car"
Output: false
Explanation: "raceacar" is not a palindrome.
```

**Example 3:**
```
Input: s = " "
Output: true
Explanation: s is an empty string "" after removing non-alphanumeric characters.
Since an empty string reads the same forward and backward, it is a palindrome.
```

**Constraints:**
```
~ 1 <= s.length <= 2 * 10^5
~ s consists only of printable ASCII characters.
```

**Comment by awsmdeep** [comment]
@vivekPatil45 can uu assign me this work

**Comment by Harsh76200** [comment]
@vivekPatil45 let me solve it..

**Comment by Mr-Yash-beldar** [comment]
@vivekPatil45 Assign this to me

**Comment by vivekPatil45** [comment]
@Mr-Yash-beldar solve it
