### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#94]
###  Give File Name :  `QuickSort`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Quick Sort](https://practice.geeksforgeeks.org/problems/quick-sort/1)

![Difficulty: Medium](https://img.shields.io/badge/Difficulty-Medium-yellow)

Quick Sort is a Divide and Conquer algorithm. It picks an element as a pivot and partitions the given array around the picked pivot.
Given an array arr[], its starting position is low (the index of the array) and its ending position is high(the index of the array).

Note: The low and high are inclusive.

Implement the partition() and quickSort() functions to sort the array.

**Example 1:**
```
Input: 
N = 5 
arr[] = { 4, 1, 3, 9, 7}
Output:
1 3 4 7 9
```
**Example 2:**
```
Input: 
N = 9
arr[] = { 2, 1, 6, 10, 4, 1, 3, 9, 7}
Output:
1 1 2 3 4 6 7 9 10
```

```
Expected Time Complexity: O(N*logN)
Expected Auxiliary Space: O(logN)
```

**Comment by Shreshth-Srivastava** [comment]
Hey there, I would like to contribute to this repository so please assign this issue to me.

**Comment by awsmdeep** [comment]
hi @vivekPatil45 i hope uu are doing well , can uu plz assign me this work

**Comment by Vvvv77777** [comment]
Hi, @vivekPatil45 Can you please assign this to me?Thanks

**Comment by gilbert-keter** [comment]
Please assign the java issue to me sir.

**Comment by Dinesh-Deore1** [comment]
assign this issue to me.

**Comment by vivekPatil45** [comment]
@Dinesh-Deore1 solve it
