### ISSUE TITLE
Union of Two Sorted Arrays

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#95]
###  Give File Name :  `filename`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Union of Two Sorted Arrays](https://practice.geeksforgeeks.org/problems/union-of-two-sorted-arrays-1587115621/1)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Union of two arrays can be defined as the common and distinct elements in the two arrays.
Given two sorted arrays of size n and m respectively, find their union.

**Example 1:**
```
Input: 
n = 5, arr1[] = {1, 2, 3, 4, 5}  
m = 3, arr2 [] = {1, 2, 3}
Output: 1 2 3 4 5
Explanation: Distinct elements including 
both the arrays are: 1 2 3 4 5.
```
**Example 2:**
```
Input: 
n = 5, arr1[] = {2, 2, 3, 4, 5}  
m = 5, arr2[] = {1, 1, 2, 3, 4}
Output: 1 2 3 4 5
Explanation: Distinct elements including 
both the arrays are: 1 2 3 4 5.
```

**Example 2:**
```
Input:
n = 5, arr1[] = {1, 1, 1, 1, 1}
m = 5, arr2[] = {2, 2, 2, 2, 2}
Output: 1 2
Explanation: Distinct elements including 
both the arrays are: 1 2
```

```
Expected Time Complexity: O(n+m).
Expected Auxiliary Space: O(n+m).
 
```

**Comment by 1Mangesh1** [comment]
Assign me @vivekPatil45

**Comment by 12345rams** [comment]
@vivekPatil45 I would like to contribute to this issue. Could you please assign this task to me.

**Comment by vivekPatil45** [comment]
@1Mangesh1 solve it

**Comment by 1Mangesh1** [comment]
#100 fixed
