### ISSUE TITLE
Counting frequencies of array elements

### ISSUE THREAD

**Issue by vivekPatil45** [Akatsuki-Coding-Club/Data-Structures-Algorithms-Akatsuki-Coding-CLub#96]
###  Give File Name :  `filename`  ✅ In respective language folder  

# 📑 DESCRIPTION

## [Counting frequencies of array elements](https://www.geeksforgeeks.org/counting-frequencies-of-array-elements/)

![Difficulty: Easy](https://img.shields.io/badge/Difficulty-Easy-brightgreen)

Given an array which may contain duplicates, print all elements and their frequencies.

**Example 1:**
```
Input :  arr[] = {10, 20, 20, 10, 10, 20, 5, 20}
Output : 10 3
         20 4
         5  1
```

```
Time Complexity : O(n) 
```

**Comment by Odin5133** [comment]
Can you assign this to me?

**Comment by Aishvarya-B** [comment]
@vivekPatil45  I would like to contribute to this issue. Could you please assign this task to me.

**Comment by Vvvv77777** [comment]
@vivekPatil45 Hi,can you please assign this issue to me,thanks!

**Comment by rayone08** [comment]
Hi! @vivekPatil45 , I have finished this task. Can you assign this to me?

**Comment by Mr-Yash-beldar** [comment]
@vivekPatil45 Please assign this issue to me

**Comment by vivekPatil45** [comment]
@Mr-Yash-beldar solve it
